### ISSUE TITLE
Certificate error ignore

### ISSUE THREAD

**Issue by bck01215** [wbh1/attunity_exporter#2]
If the cert is invalid the exporter fails. You can add a flag to allow the user to ignore the cert.
I lines 78-79 in collector.go
```
func NewAttunityCollector(cfg *Config, ignoreCert bool) *AttunityCollector {
	http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: ignoreCert}
```
In lines 88-94
```
	if !*http2 {
		transport := &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: ignoreCert},
			TLSNextProto:    make(map[string]func(authority string, c *tls.Conn) http.RoundTripper),
		}
		client.Transport = transport
	}
```
Attempted to create PR, but received permission denied

**Comment by wbh1** [comment]
Weird. Everyone should be able to open PRs. Regardless, I've added you as a collaborator (pending your invite acceptance) which will grant much more access.

> Collaborators can perform a number of actions into someone else’s personal repositories, they have gained access to. Some of them are, 
> 
> - Create, merge, and close pull requests in the repository
> - Publish, view, install the packages
> - Fork the repositories
> - Make the changes on the repositories as suggested by the Pull requests.
> - Mark issues or pull requests as duplicate
> - Create, edit, and delete any comments on commits, pull requests, and issues in the repository
> - Removing themselves as collaborators on the repositories.
> - Manage releases in the repositories.

**Comment by bck01215** [comment]
#3 resolved by  [Add ignore-cert flag option](https://github.com/wbh1/attunity_exporter/pull/3)
